services:
 ### Catalog API
  catalog.api:
    container_name: app-product    
    environment:     
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionString=mongodb://mongodb:27017"
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mongodb     
 
 ### Basket API
  # basket.api:
  #   container_name: app-basket
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - "CacheSetting:ConnectionString=redisdb:6379"
  #     - "GrpcSettings:DiscountUrl=app-discount-grpc"
  #   ports:
  #     - "8081:8080"
  #   networks:
  #     - app-network
  #   depends_on:
  #     - redisdb     
      
  discount.api:
    container_name: app-discount
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionString=Host=postgresdb;Port=5432;Database=discountdb;Username=admin;Password=admin1234"
    ports:
      - "8082:8080"
    networks:
      - app-network 
    depends_on:
      - postgresdb

  discount.grpc:
    container_name: app-discount-grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080  
      - "DatabaseSettings:ConnectionString=Host=postgresdb;Port=5432;Database=discountdb;Username=admin;Password=admin1234" 
    ports:
      - "8083:8080"
    networks:
      - app-network 
    depends_on:
      - postgresdb

 ### MongoDB
  mongodb:
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network    
    volumes:
      - mongodb-data:/data/db

 ### Redis
  redisdb:
    container_name: redisdb
    restart: always
    ports:
      - 6379:6379
    networks:
      - app-network
  
 ### Postgres
  postgresdb:
    container_name: postgresdb
    restart: always
    ports:
      - 5432:5432
    networks:
      - app-network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: discountdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
 ### PgAdmin
  pgadmin:
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "ads.junio@hotmail.com"
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - 5050:80
    networks:
      - app-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin