### Redes
networks:
  app-network:
    name: app-network
    driver: bridge
### Volumes
volumes:
      mongodb-data:
### Services
services:
  catalog.api:    
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile    

  mongodb:    
    image: mongo 
    
  basketdb:
    image: redis:alpine 

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: Basket.API
      dockerfile: Dockerfile



