### Redes
networks:
  app-network:
    name: app-network
    driver: bridge
### Volumes
volumes:
      mongodb-data:
      postgres-data:
      pgadmin-data:
### Services
services:
  catalog.api:    
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile  
      
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: Basket.API
      dockerfile: Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Discount.Grpc/Dockerfile

  mongodb:    
    image: mongo 
    
  redisdb:
    image: redis:alpine
    
  postgresdb:
    image: postgres:alpine
  
  pgadmin:
    image: dpage/pgadmin4    

  


  

